version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/myapp_dev
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
